ipc = on
splash = false

# TODO: Update paths and monitor names after copying wallpapers
preload = ~/wallpapers/who_are_you.png
preload = ~/wallpapers/alter-confrontation.jpg
preload = ~/wallpapers/alter_double-side.jpeg
preload = ~/wallpapers/alter-page4-sc1.jpeg

wallpaper = DP-3, ~/wallpapers/who_are_you.png
wallpaper = HDMI-A-1, ~/wallpapers/alter-confrontation.jpg
wallpaper = DP-1, ~/wallpapers/alter_double-side.jpeg
wallpaper = DP-2, ~/wallpapers/alter-page4-sc1.jpeg
