# Font
font_family JetBrainsMono Nerd Font
font_size 13

# Behavior
copy_on_select yes
shell /usr/bin/zsh
cursor_shape underline
cursor_trail 100
cursor_trail_color #c1a9d9

# Scrollbar
scrollbar_interactive yes
scrollbar_handle_opacity 0.3
scrollbar_gap 0.7
scrollbar_handle_color foreground

# Opacity
background_opacity 0.98
dim_opacity 0.4

# Colorscheme - Purple Focused
background  #24283b
foreground  #c0caf5
cursor      #C58AFF
selection_background  #555e8f
selection_foreground  none

# ANSI Colors
color0  #1B1E23
color1  #D2556A
color2  #4DD0A0
color3  #FFCE5C
color4  #8d91d9
color5  #C58AFF
color6  #A78AFF
color7  #E8E8E8

# Bright ANSI Colors
color8  #444A55
color9  #FF7B9C
color10 #89EFC9
color11 #FFE799
color12 #B497E8
color13 #E8ABFF
color14 #CDA6FF
color15 #FFFFFF

# Emoji support
symbol_map U+1F300-U+1F5FF Noto Color Emoji
symbol_map U+1F600-U+1F64F Noto Color Emoji
symbol_map U+1F900-U+1F9FF Noto Color Emoji
